// examples/with-nuxt/components/Header.vue
<script setup lang="ts">
const { data: posts } = await useAsyncData(
  () => queryContent().limit(3).sort({ createdAt: -1 }).find(),
)
</script>

<template>
  <header>
    <nav class="flex flex-wrap items-center justify-between">
      <NuxtLink href="/" class="transition-transform active:scale-95">
        Nuxt Example
      </NuxtLink>

      <div class="flex items-center gap-4 sm:gap-6">
        <NuxtLink v-for="post in posts" :key="post._id" class="transition-transform active:scale-95" :href="post._path">
          {{ post.shortTitle }}
        </NuxtLink>
      </div>
    </nav>
  </header>
</template>

// examples/next-example/src/components/Header.tsx
import Link from "next/link";
import { allPosts } from "~/contentlayer";

export function Header() {
  const posts = allPosts.filter((post) => post.published).sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()).slice(0, 3);
  return (
    <header>
  <nav className="flex flex-wrap items-center justify-between">
    <Link href="/" className="transition-transform active:scale-95">
      NextJS Example
    </Link>

    <div className="flex items-center gap-4 sm:gap-6">
      {posts.map((post) => (
        <Link className="transition-transform active:scale-95" href={`/${post.slug}`} key={post._id}>
          {post.shortTitle}
        </Link>
      ))}
    </div>
  </nav>
</header>
  );
}
