// examples/with-nuxt/components/Footer.vue
<script setup lang="ts">
import {
  url,
} from "../.lesetid/example.json"
</script>

<template>
  <footer class="mt-8 border-t border-t-neutral-700 pt-8 text-center flex items-center justify-between gap-2 px-4">
    <p>Nuxt Example</p>
    <ul>
      <li class="flex items-center gap-2">
        <NuxtLink to="/sitemap.xml" aria-label="sitemap">
          <Icon name="mdi:sitemap" class="size-5" />
        </NuxtLink>
        <NuxtLink :to="`https://github.com/luxass/lesetid/blob/main${url}`" aria-label="github">
          <Icon name="mdi:github" class="size-5" />
        </NuxtLink>
      </li>
    </ul>
  </footer>
</template>

// examples/with-next/components/Footer.tsx
import Link from "next/link";
import type { SVGProps } from "react";
import {
  url,
} from "../.lesetid/example.json";

export function Footer() {
  return (
    <footer className="mt-8 flex items-center justify-between gap-2 border-t border-t-neutral-700 px-4 pt-8 text-center">
      <p>NextJS Example</p>
      <ul>
        <li className="flex items-center gap-2">
          <Link href="/sitemap-index.xml" aria-label="sitemap">
            <MdiSitemap className="size-5" />
          </Link>
          <Link href={`https://github.com/luxass/lesetid/blob/main${url}`} aria-label="github">
            <MdiGithub className="size-5" />
          </Link>
        </li>
      </ul>
    </footer>

  );
}

export function MdiSitemap(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" {...props}><path fill="currentColor" d="M9 2v6h2v3H5c-1.11 0-2 .89-2 2v3H1v6h6v-6H5v-3h6v3H9v6h6v-6h-2v-3h6v3h-2v6h6v-6h-2v-3c0-1.11-.89-2-2-2h-6V8h2V2z"></path></svg>
  );
}

export function MdiGithub(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M12 2A10 10 0 0 0 2 12c0 4.42 2.87 8.17 6.84 9.5c.5.08.66-.23.66-.5v-1.69c-2.77.6-3.36-1.34-3.36-1.34c-.46-1.16-1.11-1.47-1.11-1.47c-.91-.62.07-.6.07-.6c1 .07 1.53 1.03 1.53 1.03c.87 1.52 2.34 1.07 2.91.83c.09-.65.35-1.09.63-1.34c-2.22-.25-4.55-1.11-4.55-4.92c0-1.11.38-2 1.03-2.71c-.1-.25-.45-1.29.1-2.64c0 0 .84-.27 2.75 1.02c.79-.22 1.65-.33 2.5-.33c.85 0 1.71.11 2.5.33c1.91-1.29 2.75-1.02 2.75-1.02c.55 1.35.2 2.39.1 2.64c.65.71 1.03 1.6 1.03 2.71c0 3.82-2.34 4.66-4.57 4.91c.36.31.69.92.69 1.85V21c0 .27.16.59.67.5C19.14 20.16 22 16.42 22 12A10 10 0 0 0 12 2"></path>
    </svg>
  );
}
