// examples/astro-example/src/components/Code.vue
<template>
  <code
    class="[letter-spacing:-0.02em] rounded text-sm after:(font-black text-blue-600) before:(font-black text-blue-600)"
  >
    <slot />
  </code>
</template>

<style>
code::before,
code::after {
  content: "`";
}

pre {
  --at-apply: "[tab-size:2] overflow-x-auto rounded p-4 text-sm [&code]:(text-base after:content-none before:content-none) [letter-spacing:unset]";
}

pre code::before,
pre code::after {
  content: none;
}
</style>

// examples/with-next-contentlayer/src/components/mdx/Code.tsx
type HTMLCodeElement = HTMLElement

export type CodeBlockProps = React.DetailedHTMLProps<
  React.HTMLAttributes<HTMLCodeElement>,
  HTMLCodeElement
>

export function CodeBlock({ children, ...props }: CodeBlockProps) {
  return (
    <code
      className="rounded text-sm [letter-spacing:-0.02em] before:font-black before:text-blue-600 after:font-black after:text-blue-600"
      {...props}
    >
      {children}
    </code>
  )
}
