// examples/astro-example/src/components/Code.vue
<template>
  <code
    class="[letter-spacing:-0.02em] rounded text-sm after:(font-black text-blue-600) before:(font-black text-blue-600)"
  >
    <slot />
  </code>
</template>

<style>
code::before,
code::after {
  content: "`";
}

pre {
  --at-apply: "[tab-size:2] overflow-x-auto rounded p-4 text-sm [&code]:(text-base after:content-none before:content-none) [letter-spacing:unset]";
}

pre code::before,
pre code::after {
  content: none;
}
</style>

// examples/next-example/src/components/mdx/Code.tsx
export type CodeBlockProps = React.DetailedHTMLProps<
  React.HTMLAttributes<HTMLPreElement>,
  HTMLPreElement
> & {
  raw?: string
};

export function CodeBlock({ children, raw, ...props }: CodeBlockProps) {
  return (
    <div className="codeblock">
      <pre
        className="[tab-size:2] overflow-x-auto rounded p-4 text-sm [&code]:text-base [&code]:after:content-none [&code]:before:content-none [letter-spacing:unset]"
        {...props}
      >
        {children}
      </pre>
    </div>
  );
}
